UPDATED: README.md, simplechroot, simplechroot.completion
Updated:
- Improved partition listing
- Changed -d for root partition/directory to -r

diff --git a/simplechroot b/simplechroot
--- a/simplechroot
+++ b/simplechroot
@@ -21,7 +21,7 @@
 
 mountNode=false
 _verbose=false
-version=0.0.1
+version=1.0.0
 
 if [ ! "$(id -u)" = 0 ]
 then
@@ -139,11 +139,11 @@ done
 
 if [ "$reinstallgrub" = true ]
 then
-	if [[ ! -e "$rootDir/usr/sbin/grub${grubver}-install" ]]
+	if [[ ! -e "$rootDir/usr/sbin/grub${grubver}-install" ]] || [[ ! -e "$rootDir/usr/sbin/grub${grubver}-mkconfig" ]]
 	then
 		echo "Cannot find standard Linux filesystem folders or programs."
 		echo "The system which you are trying to repair most likely uses grub2."
-		echo "Try 'simplechroot -d $_rootDir -b $bootDir --reinstall-grub 2'"
+		echo "Try 'simplechroot -r $_rootDir -b $bootDir --reinstall-grub 2'"
 		exit 1
 	fi
 fi
@@ -185,50 +185,66 @@ fi
 
 function listPartitions() {
 # list partitions that are mountable
+partitionList=""
+partCount=0
+echo "Listing partitions which should be usable"
+echo "-----------------------------------------"
 while read o
 do
 	o_cut=$(echo $o | cut -d ' ' -f1 )
 	o_basename=$(basename $o_cut)
-	if echo "sr0" | grep -q "$o_basename" || ! lsblk | grep -q "$o_basename" || [[ "$o_basename" = "loop"* ]] || ( [[ ! "${o_basename#${o_basename%?}}" = [[:digit:]] ]] && [[ ! $(dirname $o_cut) = "/dev/mapper" ]]  && [[ ! $(dirname $o_cut) = "/dev/dm"* ]] ) || [[ $(echo $o | cut -d ' ' -f2) = "swap" ]] || [[ $(echo $o | cut -d ' ' -f2) = "LVM"* ]] || [[ $(echo $o | cut -d ' ' -f2) = "ntfs" ]] || [[ $(echo $o | cut -d ' ' -f2) = "hfs"* ]] || [[ $(echo $o | cut -d ' ' -f2) = "apfs" ]]  || [[ $(echo $o | cut -d ' ' -f2) = "fat"* ]]
+	if echo "sr0" | grep -q "$o_basename" || ! lsblk | grep -q "$o_basename" || [[ "$o_basename" = "loop"* ]] || ( [[ ! "${o_basename#${o_basename%?}}" = [[:digit:]] ]] && [[ ! $(dirname $o_cut) = "/dev/mapper" ]] && [[ ! $(dirname $o_cut) = "/dev/dm"* ]] ) || echo "swap LVM2_member ntfs hfs hfs+ apfs" | grep -q "$(echo $o | cut -d ' ' -f2)" || echo "$partitionList" | grep -q "$o_cut"
 	then
 		continue
 	fi
+	partitionList="${partitionList} $o_cut"
 	if grep -q "$o_cut" /etc/mtab
 	then
-		echo "$o_cut    (already mounted)"
+		echo "[${partCount}-m.] $o_cut    (already mounted)"
+		partCount=$((partCount += 1))
 		continue
 	fi
-	if ! mount "$o_cut" /mnt
+	if ! mount "$o_cut" /mnt > /dev/null 2>&1
 	then
-		echo "$o_cut    (was unable to mount)"
+		echo "[${partCount}-!!] $o_cut    (was unable to mount)"
+		partCount=$((partCount += 1))
 		continue
 	fi
 	if NOECHO=true validate_fsDir "/mnt"
 	then
-		echo "$o_cut    (probably an installed Linux system)"
+		if [ -e '/mnt/boot/grub'*'/grub.cfg' ]
+		then
+			echo "[${partCount}-rb] $o_cut    (probably an installed Linux system with grub)"
+		else
+			echo "[${partCount}-r.] $o_cut    (probably an installed Linux system)"
+		fi
+		partCount=$((partCount += 1))
 		umount -f /mnt
 		continue
 	fi
-	if ls /mnt | grep -q "grub"
+	if [ -e '/mnt/grub'*'/grub.cfg' ]
 	then
-		echo "$o_cut    (probably a Linux boot partition)"
+		echo "[${partCount}-b.] $o_cut    (probably a Linux boot partition)"
 		umount -f /mnt
+		partCount=$((partCount += 1))
 		continue
 	fi
-	echo "$o_cut       (neither an installed Linux system or boot partition)"
+	echo "[${partCount}-??] $o_cut       (neither an installed Linux system or boot partition, could be a data partition such as a home partition)"
 	if ! umount -f /mnt
 	then
-		echo "$o_cut    (was unable to unmount)"
+		echo "[${partCount}-!!] $o_cut    (was unable to unmount)"
+		partCount=$((partCount += 1))
 		exit 1
 	fi
 done < <(lsblk -rpf | sed -n '1!p' && realpath /dev/mapper/*)
+echo "-----------------------------------------"
 }
 
 # parse args
 while [ $# -gt 0 ]
 do
 	case "$1" in
-		-d)
+		-r)
 			# root directory or node
 			shift
 			_rootDir="$1"
@@ -248,7 +264,7 @@ do
 			reinstallgrub=true
 			if [ -z "$bootDir" ] || [ -z "$_rootDir" ]
 			then
-				echo "Error: arg '-b' and '-d' must be used. It is required for reinstalling grub."
+				echo "Error: args '-r' and '-b' must be used. It is required for reinstalling grub. If the system has a single partition, just specify in '-r' and '-b'"
 				exit 1
 			fi
 			bootDir_base=$(lsblk -no pkname --path $bootDir)
@@ -278,21 +294,21 @@ do
 			echo "simplechroot ($version)"
 			echo
 			echo "Usage examples:"
-			echo "	simplechroot -d /dev/sda2 -b /dev/sda1"
-			echo "	simplechroot -d /mnt/rootMount"
-			echo "	simplechroot -d /mnt/mapper/lvmPartition"
-			echo "	simplechroot -d /mnt/rootMount -b /dev/sda1"
-			echo "	simplechroot -d /dev/sda2 -b /dev/sda1 --reinstall-grub"
-			echo "	simplechroot -d /mnt/rootMount -b /dev/sda1 -c 'ls /bin/.'"
+			echo "	simplechroot -r /dev/sda2 -b /dev/sda1"
+			echo "	simplechroot -r /mnt/rootMount"
+			echo "	simplechroot -r /mnt/mapper/lvmPartition"
+			echo "	simplechroot -r /mnt/rootMount -b /dev/sda1"
+			echo "	simplechroot -r /dev/sda2 -b /dev/sda1 --reinstall-grub"
+			echo "	simplechroot -r /mnt/rootMount -b /dev/sda1 -c 'ls /bin/.'"
 			echo
 			echo "==========================================================="
-			echo "| -l               | list partitions                      |"
-			echo "| -d               | mounted root partition or devfs node |"
+			echo "| -l               | list partitions and LVM partitions   |"
+			echo "| -r               | mounted root partition or devfs node |"
 			echo "| -b               | boot partition devfs node            |"
 			echo "| -v               | make output verbose                  |"
 			echo "| -c               | send a command to the chroot         |"
 			echo "| --reinstall-grub | reinstall grub (requires -b)         |"
-			echo "|                  | pass 2, for use in grub2-install     |"
+			echo "|                  | use '--reinstall-grub 2', for grub2  |"
 			echo "==========================================================="
 			echo
 			echo "To find your disks, use 'simplechroot -l' or your disk manager of choice."
@@ -305,7 +321,7 @@ done
 
 if [ -z "$_rootDir" ]
 then
-	echo "Error: please enter root directory or node using the '-d' arg."
+	echo "Error: please enter root directory or node using the '-r' arg."
 	exit 1
 fi
 
